### ISSUE TITLE
Integration with TouK/ThrowingFunction?

### ISSUE THREAD

**Issue by pivovarit** [jasongoodwin/better-java-monads#17]
I noticed you created a set of 3 functional types with signatures that support throwing Throwables.
I have my own project that already defined a complete set of functional types that support throwing Throwables. I think it might be worth considering reusing stuff that has already been done

https://github.com/TouK/ThrowingFunction

**Comment by jasongoodwin** [comment]
It's a good suggestion and a useful lib - if the interfaces weren't already there I'd use this approach. 

I read this article recently - http://www.mikeperham.com/2016/02/09/kill-your-dependencies/ - and while I criticized the position somewhat on hacker news, I tend to think in this case that his argument holds true - by adding another dependency the tree of code grows and the unknown increases for the end user. If it was eg json processing I'd thoroughly agree to remove it for a more tried approach but in this case it's just a couple SAMs where there is no logic to cover with tests, evolve, or maintain. For using the library, the cost for the user of having another (even if useful) library is higher than the maintenance benefit to me of removing the code I think. Hopefully oracle fix java8 because imo it has some serious omissions!!

I starred the library and will leave this issue open for a bit for consideration and discussion. The one plus is that it would clear the garbage out of the package if we used this library making the API a bit cleaner. The library also promises to only be throwing interfaces.

Open to discussing this further - I just read that article mentioned so that's fresh in my mind as when making decisions like this (again not sure I 100% agree with it though - abstraction is the benefit gained from modular code and having an abstraction that deals with throwable functional interfaces does make sense - it should be in the core lib though).
