### ISSUE TITLE
Inability to do kind of pattern match

### ISSUE THREAD

**Issue by kelebra** [jasongoodwin/better-java-monads#18]
Hi,

first of all thanks a lot for such an important monads implementation! I do have a question though: you made your `Success` and `Failure` classes as package local so that it gives no opportunity to "pattern match" (using java's `instanceOf`). I do see that your API is inspired by scala but unfortunately with a good encapsulation you sacrificed the ability to match and therefore get the actual exception from `Failure`.

Can it be changed or you would like to keep it as it is? Otherwise I would be more than glad to provide a pull request.

**Comment by jasongoodwin** [comment]
You can provide a pr if you have an idea. But I would suggest that using
try with conditionals may not be the best way to use the types. Eg using an
if statement with isInstanceOf is probably worse that composing the methods
to handle the value. If you provide a pr with a unit test demonstrating the
approach, or even a proposed snippet with the syntax you would like to use
then we can look at it and evaluate.

But otherwise I'm not averse to making it public.

**Comment by Joe0** [comment]
I suspect what you want is Either, not Try. Try should be used when the operation is recoverable; Either should be used when you can't always recover.
